### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Alfons-Hetler** [Sorrow446/PS4-OPKG-Update-Downloader#1]
I think the problem ist that he not become a key from Orbis.
Said after press my Number for the Version:
Error Line 181 main(cusa)
Error Line 140 urls = get_urls(key)
Error Line 108 raise Exception(´Bad response`)

I hope you can fix it.
Thanks.

**Comment by Sorrow446** [comment]
Pushed fix to source and binary.
